// <auto-generated />
namespace BanglaBazarFoodCourt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedvalidationforalltables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedvalidationforalltables));
        
        string IMigrationMetadata.Id
        {
            get { return "201712110756446_Added validation for all tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
